// <define:__ROUTES__>
var define_ROUTES_default = {
  version: 1,
  description: "Generated by @sveltejs/adapter-cloudflare",
  include: [
    "/*"
  ],
  exclude: [
    "/_app/*",
    "/favicon.png"
  ]
};

// node_modules/.pnpm/wrangler@3.78.9_@cloudflare+workers-types@4.20240924.0/node_modules/wrangler/templates/pages-dev-pipeline.ts
import worker from "I:\\webapps\\portfolio\\svelte\\anime-db-svelte\\.wrangler\\tmp\\pages-YfgdoM\\bundledWorker-0.7896456449691276.mjs";
import { isRoutingRuleMatch } from "I:\\webapps\\portfolio\\svelte\\anime-db-svelte\\node_modules\\.pnpm\\wrangler@3.78.9_@cloudflare+workers-types@4.20240924.0\\node_modules\\wrangler\\templates\\pages-dev-util.ts";
export * from "I:\\webapps\\portfolio\\svelte\\anime-db-svelte\\.wrangler\\tmp\\pages-YfgdoM\\bundledWorker-0.7896456449691276.mjs";
var routes = define_ROUTES_default;
var pages_dev_pipeline_default = {
  fetch(request, env, context) {
    const { pathname } = new URL(request.url);
    for (const exclude of routes.exclude) {
      if (isRoutingRuleMatch(pathname, exclude)) {
        return env.ASSETS.fetch(request);
      }
    }
    for (const include of routes.include) {
      if (isRoutingRuleMatch(pathname, include)) {
        if (worker.fetch === void 0) {
          throw new TypeError("Entry point missing `fetch` handler");
        }
        return worker.fetch(request, env, context);
      }
    }
    return env.ASSETS.fetch(request);
  }
};
export {
  pages_dev_pipeline_default as default
};
//# sourceMappingURL=7e2hg84ji5n.js.map
